version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "02:00"
      timezone: Europe/Oslo
    commit-message:
      prefix: "[github-actions] "

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 5
    groups:
      all-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
    commit-message:
      prefix: fix(npm)
